"""The SQL tokenizer.

Hand-written rather than pulled from a dependency: the inputs are small and generated by
pg_catalog, and a tokenizer we own is fully testable and cannot change its mind between
versions. Everything downstream — whitespace collapsing, cast stripping, schema remapping —
relies on it never confusing text inside a literal for SQL.
"""

import pytest

from cumo_schema_comparer.normalize.tokenizer import TokenType, tokenize


def kinds(sql):
    return [t.type for t in tokenize(sql)]


def texts(sql):
    return [t.text for t in tokenize(sql)]


class TestLiterals:
    def test_a_string_literal_is_one_token(self):
        tokens = tokenize("'hello world'")
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.STRING
        assert tokens[0].text == "'hello world'"

    def test_a_doubled_quote_is_an_escape_not_a_terminator(self):
        tokens = tokenize("'it''s fine'")
        assert len(tokens) == 1
        assert tokens[0].text == "'it''s fine'"

    def test_a_dollar_quoted_body_is_one_token(self):
        tokens = tokenize("$$ SELECT 'a'; -- not a comment $$")
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.STRING

    def test_a_tagged_dollar_quote_only_ends_on_its_own_tag(self):
        sql = "$body$ begin $$ inner $$ end $body$"
        tokens = tokenize(sql)
        assert len(tokens) == 1
        assert tokens[0].text == sql

    def test_an_escape_string_literal_honours_backslash(self):
        tokens = tokenize(r"E'line\'s end'")
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.STRING

    def test_sql_inside_a_literal_is_not_tokenized(self):
        # This is the property everything else depends on.
        tokens = tokenize("'public.users::text'")
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.STRING

    def test_an_unterminated_literal_is_returned_as_is_rather_than_raising(self):
        # Catalog output is well-formed, but a malformed value must never crash a report.
        tokens = tokenize("'unterminated")
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.STRING


class TestIdentifiers:
    def test_a_quoted_identifier_is_one_token_and_keeps_its_case(self):
        tokens = tokenize('"cumo-invoicing"."MyTable"')
        assert [t.text for t in tokens] == ['"cumo-invoicing"', ".", '"MyTable"']
        assert tokens[0].type is TokenType.IDENTIFIER

    def test_a_doubled_double_quote_is_an_escape(self):
        tokens = tokenize('"weird""name"')
        assert len(tokens) == 1
        assert tokens[0].text == '"weird""name"'

    def test_a_bare_word_is_a_word_token(self):
        assert kinds("nextval") == [TokenType.WORD]

    def test_a_dotted_reference_splits_into_words_and_punctuation(self):
        assert texts("public.gen_uuid") == ["public", ".", "gen_uuid"]


class TestOperatorsAndNumbers:
    def test_a_cast_is_a_single_operator_token(self):
        tokens = tokenize("'x'::text")
        assert [t.type for t in tokens] == [TokenType.STRING, TokenType.OPERATOR, TokenType.WORD]
        assert tokens[1].text == "::"

    @pytest.mark.parametrize("sql", ["1", "1.5", "-1", "1e6", "1.5e-3"])
    def test_numbers_are_single_tokens(self, sql):
        tokens = [t for t in tokenize(sql) if t.type is not TokenType.OPERATOR]
        assert len(tokens) == 1
        assert tokens[0].type is TokenType.NUMBER

    def test_parentheses_are_their_own_tokens(self):
        assert texts("(a)") == ["(", "a", ")"]

    @pytest.mark.parametrize("op", ["=", "<>", "<=", ">=", "||", "->>", "@>"])
    def test_multi_character_operators_stay_together(self, op):
        assert op in texts(f"a {op} b")


class TestWhitespaceAndComments:
    def test_whitespace_is_dropped(self):
        assert texts("a   \n\t b") == ["a", "b"]

    def test_a_line_comment_is_dropped(self):
        assert texts("a -- trailing\nb") == ["a", "b"]

    def test_a_block_comment_is_dropped(self):
        assert texts("a /* note */ b") == ["a", "b"]

    def test_nested_block_comments_are_handled(self):
        # PostgreSQL allows nesting; a naive scan to the first */ would truncate.
        assert texts("a /* outer /* inner */ still */ b") == ["a", "b"]

    def test_a_comment_marker_inside_a_literal_is_kept(self):
        tokens = tokenize("'-- not a comment'")
        assert len(tokens) == 1
        assert tokens[0].text == "'-- not a comment'"


class TestRealCatalogOutput:
    def test_a_check_constraint_as_the_server_prints_it(self):
        sql = "CHECK (((status)::text = ANY ((ARRAY['A'::character varying])::text[])))"
        tokens = tokenize(sql)
        assert any(t.text == "::" for t in tokens)
        assert any(t.text == "'A'" and t.type is TokenType.STRING for t in tokens)

    def test_a_serial_default(self):
        tokens = tokenize("nextval('\"cumo-invoicing\".invoice_id_seq'::regclass)")
        literal = next(t for t in tokens if t.type is TokenType.STRING)
        assert literal.text == "'\"cumo-invoicing\".invoice_id_seq'"

    def test_an_index_expression(self):
        assert texts("lower((email)::text)") == ["lower", "(", "(", "email", ")", "::", "text", ")"]


def test_tokens_can_be_reassembled_into_the_original_meaning():
    sql = "((status)::text = 'A'::character varying)"
    assert "".join(t.text for t in tokenize(sql)).replace(" ", "") == sql.replace(" ", "")
