"""The kinds of database object this tool knows about.

:data:`KIND_ORDER` fixes report ordering. It is the only place ordering is defined, so
console output, JSON, JUnit and HTML cannot disagree, and two runs over the same pair of
databases always produce a byte-identical report.
"""

from __future__ import annotations

from enum import StrEnum


class ObjectKind(StrEnum):
    """One kind of comparable catalog object."""

    SCHEMA = "schema"
    TABLE = "table"
    COLUMN = "column"
    CONSTRAINT = "constraint"
    INDEX = "index"
    VIEW = "view"
    MATVIEW = "matview"
    SEQUENCE = "sequence"
    ROUTINE = "routine"
    TRIGGER = "trigger"
    ENUM_TYPE = "enum_type"
    DOMAIN_TYPE = "domain_type"
    COMPOSITE_TYPE = "composite_type"
    RANGE_TYPE = "range_type"
    EXTENSION = "extension"

    @property
    def label(self) -> str:
        """Human-readable singular, for report headings."""
        return self.value.replace("_", " ")

    @property
    def plural(self) -> str:
        """Human-readable plural.

        Spelled out rather than appending an "s", which produced "1 indexs" in a real report.
        """
        return _PLURALS.get(self, self.label + "s")


#: Plurals that are not simply the label plus an "s".
_PLURALS: dict[ObjectKind, str] = {ObjectKind.INDEX: "indexes"}

#: Report order: containers before their contents, structure before behaviour.
KIND_ORDER: tuple[ObjectKind, ...] = (
    ObjectKind.SCHEMA,
    ObjectKind.TABLE,
    ObjectKind.COLUMN,
    ObjectKind.CONSTRAINT,
    ObjectKind.INDEX,
    ObjectKind.VIEW,
    ObjectKind.MATVIEW,
    ObjectKind.SEQUENCE,
    ObjectKind.ENUM_TYPE,
    ObjectKind.DOMAIN_TYPE,
    ObjectKind.COMPOSITE_TYPE,
    ObjectKind.RANGE_TYPE,
    ObjectKind.ROUTINE,
    ObjectKind.TRIGGER,
    ObjectKind.EXTENSION,
)

#: Kinds whose names are routinely auto-generated by PostgreSQL, so a name difference alone
#: is not a structural difference. Rename reconciliation applies to exactly these.
AUTO_NAMED_KINDS: frozenset[ObjectKind] = frozenset(
    {ObjectKind.INDEX, ObjectKind.CONSTRAINT, ObjectKind.TRIGGER}
)

_ORDER_INDEX = {kind: position for position, kind in enumerate(KIND_ORDER)}


def kind_sort_key(kind: ObjectKind) -> int:
    """Position of ``kind`` in :data:`KIND_ORDER`."""
    return _ORDER_INDEX[kind]
