"""The tunnel, against a real sshd and a database that cannot be reached any other way.

This is the test that matters. Every unit test around the tunnel passes with a forwarder that never
moves a byte; only this one proves traffic goes through the gateway — the PostgreSQL container
publishes no port to the host, so a connection that succeeds cannot have gone around it.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

pytest.importorskip("psycopg", reason="psycopg is required for integration tests")
paramiko = pytest.importorskip("paramiko", reason="the ssh extra is not installed")

from db_schema_comparer.config.model import SshRef  # noqa: E402
from db_schema_comparer.config.secrets import Dsn  # noqa: E402
from db_schema_comparer.db.connect import open_connection  # noqa: E402
from db_schema_comparer.errors import ConnectionFailed  # noqa: E402

from .conftest import POSTGRES_IMAGE, docker_available  # noqa: E402

pytestmark = pytest.mark.integration

SSHD_IMAGE = os.environ.get("CUMO_SCHEMA_DIFF_TEST_SSHD_IMAGE", "alpine:3.20")
#: sshd, configured here rather than taken from a prebuilt image: the obvious ready-made ones ship
#: `AllowTcpForwarding no`, and a gateway that refuses to forward is no use for testing forwarding.
SSHD_SETUP = (
    "apk add --no-cache openssh >/dev/null && "
    "ssh-keygen -A && "
    "adduser -D -s /bin/sh {user} && "
    # `adduser -D` leaves the account locked, and OpenSSH reports a locked account as an *invalid
    # user* rather than as a locked one, which sends you looking at the key instead.
    "passwd -u {user} && "
    "mkdir -p /home/{user}/.ssh && "
    'echo "$PUBKEY" > /home/{user}/.ssh/authorized_keys && '
    "chown -R {user}:{user} /home/{user}/.ssh && "
    "chmod 700 /home/{user}/.ssh && chmod 600 /home/{user}/.ssh/authorized_keys && "
    # Prepended, not appended: sshd honours the *first* occurrence of a directive, and the image
    # ships "AllowTcpForwarding no" above anything added at the end.
    "{{ echo AllowTcpForwarding yes; cat /etc/ssh/sshd_config; }} > /tmp/sshd_config && "
    "mv /tmp/sshd_config /etc/ssh/sshd_config && "
    "/usr/sbin/sshd -D -e -p 2222"
)
SSH_USER = "tunneluser"
DB_ALIAS = "db"
DB_PASSWORD = "tunnel-test-password"


if not docker_available():  # pragma: no cover - environment dependent
    pytest.skip("docker is not available", allow_module_level=True)


def _await_log(container, marker: str, timeout: float = 180.0) -> None:
    """Wait for ``marker`` on either stream.

    Both, because sshd writes "Server listening on" to stderr while postgres writes its readiness
    line to stdout, and a helper that watches one of them waits forever for the other.
    """
    import time

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        streams = container.get_logs()
        if any(marker in stream.decode("utf-8", "replace") for stream in streams):
            return
        time.sleep(0.5)
    streams = [s.decode("utf-8", "replace")[-400:] for s in container.get_logs()]
    raise TimeoutError(f"container never logged {marker!r}; out={streams[0]!r} err={streams[1]!r}")


@pytest.fixture(scope="module")
def keypair(tmp_path_factory) -> tuple[Path, str]:
    """A throwaway key, generated by ssh-keygen in the format everyone actually has.

    Not `paramiko.RSAKey.generate().write_private_key_file()`: that writes a legacy PEM which
    paramiko's own loader then refuses with "encountered RSA key, expected OPENSSH key". A real
    key on a real machine is an OpenSSH-format one, so the test should use one too.
    """
    import subprocess

    directory = tmp_path_factory.mktemp("ssh-key")
    private = directory / "id_ed25519"
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["/usr/bin/ssh-keygen", "-t", "ed25519", "-N", "", "-C", "tunnel-test", "-f", str(private)],
        check=True,
        capture_output=True,
    )
    private.chmod(0o600)
    return private, private.with_suffix(".pub").read_text().strip()


@pytest.fixture(scope="module")
def tunnelled(keypair):
    """An sshd and a PostgreSQL on one private network, with the database unpublished."""
    from testcontainers.core.container import DockerContainer
    from testcontainers.core.network import Network

    private_key, public_key = keypair
    with Network() as network:
        database = (
            DockerContainer(POSTGRES_IMAGE)
            .with_env("POSTGRES_PASSWORD", DB_PASSWORD)
            .with_env("POSTGRES_DB", "tunnel_db")
            .with_network(network)
            .with_network_aliases(DB_ALIAS)
        )
        gateway = (
            DockerContainer(SSHD_IMAGE)
            .with_env("PUBKEY", public_key)
            # A list, not a string: handed to the shell as one argument, docker's own quoting
            # cannot word-split the public key or eat an escape on the way in. It did both.
            .with_command(["sh", "-c", SSHD_SETUP.format(user=SSH_USER)])
            .with_exposed_ports(2222)
            .with_network(network)
        )
        with database, gateway:
            _await_log(database, "database system is ready to accept connections")
            # sshd announces itself on stderr, which is why both streams are searched.
            _await_log(gateway, "Server listening on")
            yield (
                SshRef(
                    host=gateway.get_container_host_ip(),
                    port=int(gateway.get_exposed_port(2222)),
                    user=SSH_USER,
                    private_key=str(private_key),
                ),
                f"postgresql://postgres:{DB_PASSWORD}@{DB_ALIAS}:5432/tunnel_db",
            )


def test_a_database_reachable_only_through_the_gateway_is_reached(tunnelled, tmp_path):
    """The database publishes no port, so this cannot have connected directly."""
    ssh, dsn_value = tunnelled
    ssh = ssh.model_copy(update={"known_hosts": str(tmp_path / "known_hosts")})
    dsn = Dsn(dsn_value, env_name="IT_TUNNEL_DSN")

    with (
        open_connection(dsn, label="tunnelled", ssh=ssh) as connection,
        connection.cursor() as cursor,
    ):
        cursor.execute("SELECT current_database() AS name")
        row = cursor.fetchone()

    assert row is not None
    assert row["name"] == "tunnel_db"


def test_the_same_database_is_unreachable_without_the_gateway(tunnelled):
    """The other half of the proof: without the tunnel this address means nothing here."""
    _, dsn_value = tunnelled
    dsn = Dsn(dsn_value, env_name="IT_TUNNEL_DSN")

    with pytest.raises(ConnectionFailed), open_connection(dsn, label="direct"):
        pass


def test_an_unknown_gateway_is_pinned_on_first_contact(tunnelled, tmp_path):
    """Trust on first use: nothing is known yet, so the key is accepted and written down."""
    ssh, dsn_value = tunnelled
    store = tmp_path / "known_hosts"
    ssh = ssh.model_copy(update={"known_hosts": str(store)})

    with open_connection(Dsn(dsn_value, env_name="IT_TUNNEL_DSN"), label="t", ssh=ssh):
        pass

    assert store.read_text().strip(), "the gateway's key should have been pinned"


def test_a_changed_host_key_is_refused_afterwards(tunnelled, tmp_path):
    """The half of trust-on-first-use that is worth having.

    A pinned gateway whose key later differs is refused outright — pinning without this would be
    theatre.
    """
    ssh, dsn_value = tunnelled
    store = tmp_path / "known_hosts"
    ssh = ssh.model_copy(update={"known_hosts": str(store)})
    dsn = Dsn(dsn_value, env_name="IT_TUNNEL_DSN")

    with open_connection(dsn, label="t", ssh=ssh):
        pass

    # Replace the pinned key with a different one of the same type, as a swapped host would.
    impostor = paramiko.RSAKey.generate(2048)
    pinned = store.read_text().split()
    store.write_text(f"{pinned[0]} ssh-rsa {impostor.get_base64()}\n")

    with pytest.raises(ConnectionFailed) as raised, open_connection(dsn, label="t", ssh=ssh):
        pass
    assert "has changed" in str(raised.value)
