"""A small SQL tokenizer.

Its only job is to tell SQL structure apart from text that merely looks like SQL. Every
canonicalisation downstream — collapsing whitespace, stripping redundant casts, requalifying
schema names — is wrong if it edits the inside of a string literal, and a function body is
full of string literals containing SQL.

Hand-written on purpose. The inputs are short and machine-generated by ``pg_catalog``, so the
grammar needed is tiny, and owning it keeps the equality relation stable: a dependency that
reformats differently between its own releases would make two runs of *this* tool disagree.

Not a parser. It never validates; malformed input tokenizes to something reasonable so a
report can still be produced.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum, auto

#: Multi-character operators, longest first so the scan is greedy.
_OPERATORS = (
    "::",
    "->>",
    "#>>",
    "->",
    "#>",
    "<>",
    "!=",
    "<=",
    ">=",
    "||",
    "@>",
    "<@",
    "&&",
    "<<",
    ">>",
    "^@",
    "~~",
    "!~",
    "=",
    "<",
    ">",
    "+",
    "-",
    "*",
    "/",
    "%",
    "^",
    "|",
    "&",
    "~",
    "!",
    "?",
    "@",
    "#",
)

_NUMBER = re.compile(r"\d+(?:\.\d*)?(?:[eE][+-]?\d+)?|\.\d+(?:[eE][+-]?\d+)?")
_WORD = re.compile(r"[A-Za-z_\u0080-￿][A-Za-z0-9_$\u0080-￿]*")
_DOLLAR_TAG = re.compile(r"\$[A-Za-z_\u0080-￿][A-Za-z0-9_\u0080-￿]*\$|\$\$")


class TokenType(Enum):
    """What a token is, at the granularity canonicalisation needs."""

    WORD = auto()
    """A bare identifier or keyword."""
    IDENTIFIER = auto()
    """A double-quoted identifier. Case and punctuation inside are significant."""
    STRING = auto()
    """A string literal, including dollar-quoted bodies. Never rewritten."""
    NUMBER = auto()
    PUNCTUATION = auto()
    """``(``, ``)``, ``,``, ``.``, ``;``, ``[``, ``]``."""
    OPERATOR = auto()


@dataclass(frozen=True, slots=True)
class Token:
    """One token and where it came from."""

    type: TokenType
    text: str
    start: int

    @property
    def is_quotable(self) -> bool:
        """Whether this token names something, i.e. may be rewritten by a schema remap."""
        return self.type in (TokenType.WORD, TokenType.IDENTIFIER)

    def lower(self) -> str:
        """Case-folded text, for keyword comparison only. Never for identifiers."""
        return self.text.lower()


_PUNCTUATION = frozenset("(),.;[]")


def tokenize(sql: str) -> list[Token]:
    """Split ``sql`` into tokens, dropping whitespace and comments.

    Comments and whitespace are dropped because nothing downstream cares about them: two
    servers print the same definition with different spacing, and a comment inside a function
    body is not part of what the body does.
    """
    tokens: list[Token] = []
    position = 0
    length = len(sql)

    while position < length:
        char = sql[position]

        if char.isspace():
            position += 1
            continue

        if sql.startswith("--", position):
            newline = sql.find("\n", position)
            position = length if newline == -1 else newline + 1
            continue

        if sql.startswith("/*", position):
            position = _skip_block_comment(sql, position)
            continue

        if char == "'":
            end = _scan_single_quoted(sql, position)
            tokens.append(Token(TokenType.STRING, sql[position:end], position))
            position = end
            continue

        # E'...' and U&'...' are string literals with their own escape rules.
        if char in "eEuUnNbBxX" and _starts_prefixed_literal(sql, position):
            prefix_end = sql.index("'", position)
            end = _scan_single_quoted(sql, prefix_end, backslash_escapes=char in "eE")
            tokens.append(Token(TokenType.STRING, sql[position:end], position))
            position = end
            continue

        if char == '"':
            end = _scan_double_quoted(sql, position)
            tokens.append(Token(TokenType.IDENTIFIER, sql[position:end], position))
            position = end
            continue

        if char == "$":
            tag_match = _DOLLAR_TAG.match(sql, position)
            if tag_match:
                end = _scan_dollar_quoted(sql, position, tag_match.group(0))
                tokens.append(Token(TokenType.STRING, sql[position:end], position))
                position = end
                continue

        if char in _PUNCTUATION:
            tokens.append(Token(TokenType.PUNCTUATION, char, position))
            position += 1
            continue

        if char.isdigit():
            number = _NUMBER.match(sql, position)
            if number:
                tokens.append(Token(TokenType.NUMBER, number.group(0), position))
                position = number.end()
                continue

        word = _WORD.match(sql, position)
        if word:
            tokens.append(Token(TokenType.WORD, word.group(0), position))
            position = word.end()
            continue

        for operator in _OPERATORS:
            if sql.startswith(operator, position):
                tokens.append(Token(TokenType.OPERATOR, operator, position))
                position += len(operator)
                break
        else:
            # Something unrecognised. Emit it rather than raising: a report must still be
            # produced even if a definition contains a character this grammar does not know.
            tokens.append(Token(TokenType.OPERATOR, char, position))
            position += 1

    return tokens


def _starts_prefixed_literal(sql: str, position: int) -> bool:
    """Whether a literal prefix such as ``E'`` or ``U&'`` begins at ``position``."""
    if sql.startswith("&'", position + 1):
        return True
    return sql.startswith("'", position + 1)


def _scan_single_quoted(sql: str, start: int, *, backslash_escapes: bool = False) -> int:
    """Index just past a ``'...'`` literal, honouring ``''`` (and optionally ``\\'``)."""
    position = start + 1
    length = len(sql)
    while position < length:
        char = sql[position]
        if backslash_escapes and char == "\\" and position + 1 < length:
            position += 2
            continue
        if char == "'":
            if sql.startswith("''", position):
                position += 2
                continue
            return position + 1
        position += 1
    return length  # Unterminated. Treat the remainder as the literal.


def _scan_double_quoted(sql: str, start: int) -> int:
    """Index just past a ``"..."`` identifier, honouring ``""``."""
    position = start + 1
    length = len(sql)
    while position < length:
        if sql[position] == '"':
            if sql.startswith('""', position):
                position += 2
                continue
            return position + 1
        position += 1
    return length


def _scan_dollar_quoted(sql: str, start: int, tag: str) -> int:
    """Index just past a dollar-quoted body.

    Only the matching tag closes it, so ``$body$ ... $$ ... $body$`` is a single literal.
    """
    end = sql.find(tag, start + len(tag))
    return len(sql) if end == -1 else end + len(tag)


def _skip_block_comment(sql: str, start: int) -> int:
    """Index just past a ``/* ... */`` comment. PostgreSQL allows these to nest."""
    depth = 0
    position = start
    length = len(sql)
    while position < length:
        if sql.startswith("/*", position):
            depth += 1
            position += 2
            continue
        if sql.startswith("*/", position):
            depth -= 1
            position += 2
            if depth == 0:
                return position
            continue
        position += 1
    return length
