-- Baseline schema applied to BOTH databases.
--
-- The most valuable test in this suite applies this file to both sides and asserts zero
-- findings at WARNING or above. Every object below therefore exists to exercise one way the
-- catalog can make two identical schemas *look* different:
--
--   * a hyphenated, quoted schema name, as cumo-invoicing really uses;
--   * a serial column, whose generated sequence name diverges between environments;
--   * an identity column, which is not the same thing as a serial;
--   * a stored generated column, whose expression lives in the default's catalog slot;
--   * a dropped column, which leaves a permanent hole in attnum;
--   * defaults spelled two ways, which pg_attrdef keeps verbatim (unlike type names, which
--     the server canonicalises for us);
--   * a mixed-case quoted identifier, which must never be case-folded.

-- Before anything that uses it: `d_func` below defaults to gen_random_uuid(), which pgcrypto
-- supplies. That function only became core in PostgreSQL 13, so creating the extension after its
-- first use happened to work on the versions CI runs and failed on 12. (This file still needs 12
-- for its generated columns; 11 has its own fixture in pg11.sql.)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS "cumo-invoicing" AUTHORIZATION CURRENT_USER;

CREATE TABLE public.mandant (
    id          integer PRIMARY KEY,
    name        character varying(80) NOT NULL,
    created_at  timestamp without time zone NOT NULL DEFAULT now(),
    active      boolean NOT NULL DEFAULT true
);

-- A serial column. This materialises as integer + nextval() on an owned sequence whose name
-- is generated, so the two databases can legitimately disagree about that name.
CREATE TABLE "cumo-invoicing".invoice (
    id            serial PRIMARY KEY,
    mandant_id    integer NOT NULL REFERENCES public.mandant (id),
    number        character varying(40) NOT NULL,
    net_amount    numeric(12,2) NOT NULL DEFAULT 0,
    tax_rate      numeric(5,4) NOT NULL DEFAULT 0.1900,
    -- Lives in the same catalog slot as a default, but is not a default.
    gross_amount  numeric(14,4) GENERATED ALWAYS AS (net_amount * (1 + tax_rate)) STORED,
    note          text,
    issued_at     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status        character varying(20) NOT NULL DEFAULT 'DRAFT'::character varying
);

-- An identity column. Autoincrements like a serial, but is a different object.
CREATE TABLE "cumo-invoicing".invoice_line (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  integer NOT NULL REFERENCES "cumo-invoicing".invoice (id),
    position    smallint NOT NULL,
    description text NOT NULL,
    amount      numeric(12,2) NOT NULL
);

-- A dropped column leaves a permanent hole in attnum. Every column after it would report
-- drift if the comparison used attnum instead of a dense ordinal.
CREATE TABLE public.audit_entry (
    id           integer PRIMARY KEY,
    obsolete     text,
    actor        character varying(64) NOT NULL,
    happened_at  timestamp with time zone NOT NULL DEFAULT now(),
    payload      text
);
ALTER TABLE public.audit_entry DROP COLUMN obsolete;

-- Mixed case and a hyphen. Neither may ever be folded or unquoted.
CREATE TABLE "cumo-invoicing"."DunningLevel" (
    id     integer PRIMARY KEY,
    "Name" character varying(40) NOT NULL
);

-- Quartz runtime state: present in the platform, ignored by default.
CREATE TABLE public."QRTZ_LOCKS" (
    sched_name  character varying(120) NOT NULL,
    lock_name   character varying(40) NOT NULL,
    PRIMARY KEY (sched_name, lock_name)
);

-- Liquibase bookkeeping, deliberately NOT in public: cumo-invoicing sets
-- liquibase-schema=cumo-invoicing, so the changelog must be located, not assumed.
CREATE TABLE "cumo-invoicing"."DATABASECHANGELOG" (
    "ID"            character varying(255) NOT NULL,
    "AUTHOR"        character varying(255) NOT NULL,
    "FILENAME"      character varying(255) NOT NULL,
    "DATEEXECUTED"  timestamp without time zone NOT NULL,
    "ORDEREXECUTED" integer NOT NULL,
    "EXECTYPE"      character varying(10) NOT NULL,
    "MD5SUM"        character varying(35),
    "DESCRIPTION"   character varying(255),
    "COMMENTS"      character varying(255),
    "TAG"           character varying(255),
    "LIQUIBASE"     character varying(20),
    "CONTEXTS"      character varying(255),
    "LABELS"        character varying(255),
    "DEPLOYMENT_ID" character varying(10)
);

CREATE TABLE "cumo-invoicing"."DATABASECHANGELOGLOCK" (
    "ID"          integer NOT NULL PRIMARY KEY,
    "LOCKED"      boolean NOT NULL,
    "LOCKGRANTED" timestamp without time zone,
    "LOCKEDBY"    character varying(255)
);

INSERT INTO "cumo-invoicing"."DATABASECHANGELOGLOCK" VALUES (1, false, NULL, NULL);

INSERT INTO "cumo-invoicing"."DATABASECHANGELOG"
    ("ID", "AUTHOR", "FILENAME", "DATEEXECUTED", "ORDEREXECUTED", "EXECTYPE", "MD5SUM", "TAG")
VALUES
    ('initial-schema', 'kolowae', 'liquibase/initial-schema-changelog.xml',
     '2026-01-10 08:00:00', 1, 'EXECUTED', '9:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', NULL),
    ('add-invoice-line', 'kolowae', 'update_20260115.xml',
     '2026-01-15 08:00:00', 2, 'EXECUTED', '9:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', NULL),
    ('add-dunning', 'kolowae', 'liquibase/update_20260201.xml',
     '2026-02-01 08:00:00', 3, 'EXECUTED', '9:cccccccccccccccccccccccccccccccc', 'R7.6.2');

-- Phase 2: every column flavour the normaliser has to survive.
--
-- Applied to both databases, so the no-drift test asserts zero findings across all of it. Each
-- column is here because it is a distinct way the catalog can print something back differently
-- from how it was written, or a distinct kind of default.

CREATE TYPE "cumo-invoicing".dunning_stage AS ENUM ('NONE', 'FIRST', 'SECOND', 'LEGAL');
CREATE DOMAIN "cumo-invoicing".positive_amount AS numeric(12,2) CHECK (VALUE > 0);

CREATE OR REPLACE FUNCTION "cumo-invoicing".next_reference() RETURNS text
    LANGUAGE sql IMMUTABLE AS $$ SELECT 'REF-0000' $$;

CREATE TABLE "cumo-invoicing".column_flavours (
    -- Autoincrement, all three spellings. serial and identity are different objects, and
    -- ALWAYS is not BY DEFAULT.
    small_serial   smallserial,
    big_serial     bigserial,
    id_always      integer GENERATED ALWAYS AS IDENTITY,
    id_by_default  integer GENERATED BY DEFAULT AS IDENTITY,

    -- Numeric: an unconstrained numeric is NOT numeric(12,2), and an explicit zero scale is.
    amount_free    numeric,
    amount_scaled  numeric(12,2),
    amount_zero    numeric(10,0),
    amount_int     numeric(10),

    -- Character types, long spellings, and the fixed-width one.
    code_varchar   character varying(12),
    code_bpchar    character(3),
    code_text      text,

    -- Time types, with and without a precision modifier.
    ts_plain       timestamp without time zone,
    ts_tz          timestamp with time zone,
    ts_precise     timestamp(3) without time zone,
    ts_tz_precise  timestamp(3) with time zone,
    t_plain        time without time zone,
    t_tz           time with time zone,
    span           interval,
    span_precise   interval hour to second(3),

    -- Arrays. PostgreSQL does not enforce declared dimensions, so [][] and [] are one type.
    tags           text[],
    tag_matrix     integer[][],
    scores         numeric(5,2)[],

    -- Everything else with its own printing rules.
    payload        jsonb,
    legacy_payload json,
    external_id    uuid,
    raw_bytes      bytea,
    client_ip      inet,
    flags          bit varying(8),
    fixed_flags    bit(4),
    money_amount   money,
    stage          "cumo-invoicing".dunning_stage,
    vetted_amount  "cumo-invoicing".positive_amount,

    -- Defaults of every shape.
    d_literal      integer      DEFAULT 42,
    d_negative     integer      DEFAULT -1,
    d_paren        numeric(8,2) DEFAULT (0)::numeric,
    d_bool         boolean      DEFAULT false,
    d_string       character varying(16) DEFAULT 'DRAFT'::character varying,
    d_quoted       text         DEFAULT 'it''s here',
    d_now          timestamp with time zone DEFAULT now(),
    d_current      timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    d_user         character varying(64) DEFAULT CURRENT_USER,
    d_func         uuid         DEFAULT gen_random_uuid(),
    d_qualified    text         DEFAULT "cumo-invoicing".next_reference(),
    d_empty_array  text[]       DEFAULT '{}'::text[],
    d_array_items  text[]       DEFAULT ARRAY['a'::text, 'b'::text],
    d_enum         "cumo-invoicing".dunning_stage DEFAULT 'NONE',
    d_json         jsonb        DEFAULT '{}'::jsonb,
    d_expression   integer      DEFAULT (2 * 21),

    -- A stored generated column over two other columns.
    computed       numeric(14,4) GENERATED ALWAYS AS (amount_scaled * 2) STORED,

    -- A non-default collation, which must not be confused with the database's own.
    sorted_name    text COLLATE "C",

    -- NOT NULL alongside a default, so the two are not conflated.
    required       integer NOT NULL DEFAULT 0
);

-- Phase 4: constraints and indexes.
--
-- The tables above already carry primary keys and foreign keys. These add the cases that are
-- specifically hard to compare: an index whose name PostgreSQL generated, an expression index, a
-- partial index, INCLUDE columns, a non-default operator class, a descending key, a deferrable
-- constraint, and a UNIQUE constraint whose backing index must not be reported twice.

ALTER TABLE "cumo-invoicing".invoice
    ADD CONSTRAINT invoice_number_key UNIQUE (number);

ALTER TABLE "cumo-invoicing".invoice
    ADD CONSTRAINT invoice_net_amount_check CHECK (net_amount >= 0);

ALTER TABLE "cumo-invoicing".invoice
    ADD CONSTRAINT invoice_status_check
    CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'OPEN'::character varying,
                                     'PAID'::character varying]::text[]));

-- A deferrable constraint is checked at commit rather than per statement.
ALTER TABLE "cumo-invoicing".invoice_line
    ADD CONSTRAINT invoice_line_position_key UNIQUE (invoice_id, position)
    DEFERRABLE INITIALLY IMMEDIATE;

-- A foreign key with explicit referential actions. Cascading in one environment and restricting
-- in another behaves differently the first time a referenced row is deleted.
ALTER TABLE "cumo-invoicing".invoice_line
    DROP CONSTRAINT invoice_line_invoice_id_fkey;
ALTER TABLE "cumo-invoicing".invoice_line
    ADD CONSTRAINT invoice_line_invoice_id_fkey
    FOREIGN KEY (invoice_id) REFERENCES "cumo-invoicing".invoice (id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Plain index, name chosen by hand.
CREATE INDEX idx_invoice_mandant ON "cumo-invoicing".invoice (mandant_id);

-- Auto-named by PostgreSQL. This is the name that diverges between environments.
CREATE INDEX ON "cumo-invoicing".invoice (issued_at);

-- An expression index. pg_get_indexdef prints the expression from the parse tree, with its own
-- parentheses and casts.
CREATE INDEX idx_invoice_number_lower ON "cumo-invoicing".invoice (lower(number::text));

-- A partial index covers only the rows matching its condition.
CREATE INDEX idx_invoice_open ON "cumo-invoicing".invoice (issued_at)
    WHERE status::text = 'OPEN'::text;

-- A descending key with NULLS FIRST: a different usable ordering from the default.
CREATE INDEX idx_invoice_issued_desc ON "cumo-invoicing".invoice (issued_at DESC NULLS FIRST);

-- INCLUDE columns permit an index-only scan without changing what the index matches.
CREATE UNIQUE INDEX idx_invoice_number_include
    ON "cumo-invoicing".invoice (number) INCLUDE (mandant_id);

-- A non-default operator class: this one supports LIKE 'x%' and the default does not.
CREATE INDEX idx_mandant_name_pattern
    ON public.mandant (name varchar_pattern_ops);

-- A multi-column index, to pin key order.
CREATE INDEX idx_invoice_line_composite
    ON "cumo-invoicing".invoice_line (invoice_id, position DESC);

-- A GIN index on jsonb: a different access method answering different queries.
CREATE INDEX idx_flavours_payload ON "cumo-invoicing".column_flavours USING gin (payload);

-- Phase 7: views, sequences, routines, triggers and user-defined types.
--
-- Applied to both databases, so the no-drift test asserts zero findings across all of it. Several of
-- these exist specifically to prove a *filter* works:
--
--   * the foreign keys above create internal triggers; only the two user triggers below may appear;
--   * every table above creates a composite type of its own name; only `money_split` may appear;
--   * pgcrypto installs a pile of functions; only the extension row may appear. The extension
--     itself is created at the top of this file, because a default below calls one of its
--     functions.

-- A standalone composite type. The tables' row types must not be reported alongside it.
CREATE TYPE "cumo-invoicing".money_split AS (net numeric(12,2), tax numeric(12,2));

-- A range type over a domain-free base.
CREATE TYPE "cumo-invoicing".billing_period AS RANGE (subtype = date);

-- A standalone sequence, not owned by any column.
CREATE SEQUENCE "cumo-invoicing".reference_seq
    AS bigint START WITH 1000 INCREMENT BY 10 MINVALUE 1000 MAXVALUE 9999999 CACHE 20 CYCLE;

CREATE VIEW "cumo-invoicing".invoice_summary AS
SELECT i.id,
       i.number,
       i.mandant_id,
       m.name AS mandant_name,
       i.net_amount,
       i.gross_amount,
       i.status
  FROM "cumo-invoicing".invoice AS i
  JOIN public.mandant AS m ON m.id = i.mandant_id;

CREATE VIEW "cumo-invoicing".open_invoice AS
SELECT * FROM "cumo-invoicing".invoice_summary WHERE status::text = 'OPEN'::text;

CREATE MATERIALIZED VIEW "cumo-invoicing".invoice_totals AS
SELECT mandant_id, count(*) AS invoice_count, sum(net_amount) AS net_total
  FROM "cumo-invoicing".invoice
 GROUP BY mandant_id;

-- A plpgsql function with a multi-line body. Its whitespace is what the body canonicaliser has to
-- normalise away without touching the string literals.
CREATE OR REPLACE FUNCTION "cumo-invoicing".invoice_gross(p_invoice_id integer)
RETURNS numeric
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_total numeric(14,4);
BEGIN
    SELECT gross_amount INTO v_total
      FROM "cumo-invoicing".invoice
     WHERE id = p_invoice_id;

    IF v_total IS NULL THEN
        RAISE EXCEPTION 'Invoice % not found', p_invoice_id;
    END IF;

    RETURN v_total;
END;
$$;

-- An overload set. Both members must be inventoried separately, or each reports the other's body as
-- drift.
CREATE OR REPLACE FUNCTION "cumo-invoicing".describe(p_value integer) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT 'int:' || p_value $$;
CREATE OR REPLACE FUNCTION "cumo-invoicing".describe(p_value text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT 'text:' || p_value $$;

-- A SECURITY DEFINER function with a pinned search_path. Both attributes are security-relevant.
CREATE OR REPLACE FUNCTION "cumo-invoicing".mandant_count() RETURNS bigint
    LANGUAGE sql
    SECURITY DEFINER
    SET search_path = 'public'
    AS $$ SELECT count(*) FROM public.mandant $$;

-- A procedure, which is a different prokind from a function.
CREATE OR REPLACE PROCEDURE "cumo-invoicing".touch_invoice(p_invoice_id integer)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "cumo-invoicing".invoice SET issued_at = now() WHERE id = p_invoice_id;
END;
$$;

CREATE OR REPLACE FUNCTION "cumo-invoicing".stamp_issued_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.issued_at := now();
    RETURN NEW;
END;
$$;

-- A row trigger with a WHEN clause.
CREATE TRIGGER invoice_stamp_issued
    BEFORE INSERT OR UPDATE ON "cumo-invoicing".invoice
    FOR EACH ROW
    WHEN (NEW.status::text = 'OPEN'::text)
    EXECUTE FUNCTION "cumo-invoicing".stamp_issued_at();

CREATE OR REPLACE FUNCTION "cumo-invoicing".audit_statement() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RETURN NULL;
END;
$$;

-- A statement-level trigger with arguments, so both are exercised.
CREATE TRIGGER invoice_audit
    AFTER INSERT OR UPDATE OR DELETE ON "cumo-invoicing".invoice
    FOR EACH STATEMENT
    EXECUTE FUNCTION "cumo-invoicing".audit_statement('invoice', 'audit');

-- Phase 9: a partitioned table.
--
-- Its leaf partitions are created by a scheduled maintenance job, not by a migration, so production
-- legitimately holds far more of them than a development database. They are folded into a count on
-- the parent rather than inventoried individually — otherwise a prod-against-dev comparison would
-- report fifty-eight missing tables and bury everything else.
CREATE TABLE "cumo-invoicing".invoice_event (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    invoice_id  integer NOT NULL,
    occurred_at date NOT NULL,
    kind        character varying(40) NOT NULL
) PARTITION BY RANGE (occurred_at);

CREATE TABLE "cumo-invoicing".invoice_event_2026_01
    PARTITION OF "cumo-invoicing".invoice_event
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

CREATE TABLE "cumo-invoicing".invoice_event_2026_02
    PARTITION OF "cumo-invoicing".invoice_event
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

-- A partitioned index. PostgreSQL creates a child index on every leaf, so this also proves that
-- those children are not inventoried alongside it.
CREATE INDEX idx_invoice_event_invoice ON "cumo-invoicing".invoice_event (invoice_id);
