-- The table is partitioned on a different column, which is a genuine structural change: every query
-- that relied on partition pruning now scans everything.
DROP TABLE "cumo-invoicing".invoice_event;
CREATE TABLE "cumo-invoicing".invoice_event (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    invoice_id  integer NOT NULL,
    occurred_at date NOT NULL,
    kind        character varying(40) NOT NULL
) PARTITION BY RANGE (invoice_id);
CREATE TABLE "cumo-invoicing".invoice_event_low
    PARTITION OF "cumo-invoicing".invoice_event FOR VALUES FROM (0) TO (1000);
CREATE TABLE "cumo-invoicing".invoice_event_high
    PARTITION OF "cumo-invoicing".invoice_event FOR VALUES FROM (1000) TO (100000);
