-- Baseline schema for PostgreSQL 11, the oldest release this tool inspects.
--
-- `base.sql` cannot be applied to an 11: it declares `GENERATED ALWAYS AS (...) STORED` columns,
-- and one of them is read by a view and a function in that same file, so the declaration is not
-- removable. Rather than make that carefully-built fixture vary by version, 11 gets its own.
--
-- What this file is for: proving that every catalog query runs against an 11 *with rows to
-- return*. A query that selects a column the server does not have fails when it is planned, so
-- an empty database would prove the SQL parses; it would not prove that the row-shaping code
-- behind it copes with what an 11 actually sends back. Every object kind the tool compares is
-- therefore present here, and the kinds whose catalog support arrived in 11 are the point:
--
--   * `pg_index.indnkeyatts` — INCLUDE columns on an index (11);
--   * `pg_proc.prokind` — a procedure, which is not a function (11);
--   * `pg_partitioned_table` with a hash-partitioned table (11);
--   * `pg_sequence` — sequence parameters as catalog rows rather than a relation scan (10);
--   * a hyphenated quoted schema, as acme-invoicing really uses.
--
-- Deliberately absent: generated columns (12), so this file is valid on every supported version
-- and can be applied to a newer server unchanged — which is what makes an 11-against-11
-- comparison a fair test rather than a comparison of two different schemas.

CREATE SCHEMA IF NOT EXISTS "acme-invoicing" AUTHORIZATION CURRENT_USER;

CREATE TABLE public.mandant (
    id          integer PRIMARY KEY,
    name        character varying(80) NOT NULL,
    created_at  timestamp without time zone NOT NULL DEFAULT now(),
    active      boolean NOT NULL DEFAULT true
);

-- A serial column, whose owned sequence has a generated name the two databases may disagree
-- about, and an identity column, which autoincrements the same way but is a different object.
CREATE TABLE "acme-invoicing".invoice (
    id            serial PRIMARY KEY,
    mandant_id    integer NOT NULL REFERENCES public.mandant (id),
    number        character varying(40) NOT NULL,
    net_amount    numeric(12,2) NOT NULL DEFAULT 0,
    tax_rate      numeric(5,4) NOT NULL DEFAULT 0.1900,
    note          text,
    issued_at     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status        character varying(20) NOT NULL DEFAULT 'DRAFT'::character varying,
    sorted_name   text COLLATE "C",
    "MixedCase"   integer
);

CREATE TABLE "acme-invoicing".receipt (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id integer NOT NULL REFERENCES "acme-invoicing".invoice (id) ON DELETE CASCADE,
    scratch    integer,
    paid_at    timestamp with time zone,
    amount     numeric(12,2) NOT NULL CHECK (amount > 0)
);

-- A dropped column leaves a permanent hole in attnum, which must not be read as an ordinal
-- difference against a database where the hole is somewhere else.
ALTER TABLE "acme-invoicing".receipt DROP COLUMN scratch;

-- An index with INCLUDE columns: pg_index.indnkeyatts, new in 11, is what tells the key columns
-- apart from the payload. Read as one list, this index would look like a four-column key.
CREATE INDEX receipt_invoice_idx
    ON "acme-invoicing".receipt (invoice_id, paid_at) INCLUDE (amount);

-- A partial index, whose predicate the server re-prints from its parse tree.
CREATE INDEX invoice_open_idx
    ON "acme-invoicing".invoice (mandant_id)
    WHERE status <> 'PAID'::character varying;

-- An expression index, likewise re-printed.
CREATE INDEX invoice_number_lower_idx
    ON "acme-invoicing".invoice (lower(number::text));

-- Hash partitioning arrived in 11.
CREATE TABLE "acme-invoicing".ledger (
    id       integer NOT NULL,
    mandant  integer NOT NULL,
    amount   numeric(14,2) NOT NULL
) PARTITION BY HASH (mandant);

CREATE TABLE "acme-invoicing".ledger_p0
    PARTITION OF "acme-invoicing".ledger FOR VALUES WITH (MODULUS 2, REMAINDER 0);
CREATE TABLE "acme-invoicing".ledger_p1
    PARTITION OF "acme-invoicing".ledger FOR VALUES WITH (MODULUS 2, REMAINDER 1);

-- A standalone sequence, read from pg_sequence.
CREATE SEQUENCE "acme-invoicing".reference_seq
    START WITH 1000 INCREMENT BY 5 MINVALUE 1000 MAXVALUE 99999 CACHE 10 CYCLE;

-- Every user type kind the tool compares.
CREATE TYPE "acme-invoicing".dunning_stage AS ENUM ('NONE', 'FIRST', 'SECOND', 'LEGAL');
CREATE DOMAIN "acme-invoicing".positive_amount AS numeric(14,2)
    CONSTRAINT positive_amount_check CHECK (VALUE > 0);
CREATE TYPE "acme-invoicing".money_pair AS (gross numeric(14,2), net numeric(14,2));
CREATE TYPE "acme-invoicing".amount_range AS RANGE (subtype = numeric);

-- A view and a materialized view, both re-printed from the parse tree.
CREATE VIEW "acme-invoicing".open_invoice AS
    SELECT i.id,
           i.mandant_id,
           i.number,
           i.net_amount
    FROM "acme-invoicing".invoice i
    WHERE i.status <> 'PAID'::character varying;

CREATE MATERIALIZED VIEW "acme-invoicing".invoice_total AS
    SELECT i.mandant_id,
           sum(i.net_amount) AS total
    FROM "acme-invoicing".invoice i
    GROUP BY i.mandant_id;

-- A function, an overload of it, and a procedure. prokind, new in 11, is what tells the
-- procedure from the functions; before 11 it was two booleans.
CREATE FUNCTION "acme-invoicing".next_reference() RETURNS text
    LANGUAGE sql
    AS $$ SELECT 'REF-' || nextval('"acme-invoicing".reference_seq')::text $$;

CREATE FUNCTION "acme-invoicing".invoice_total(p_mandant integer) RETURNS numeric
    LANGUAGE plpgsql
    SECURITY DEFINER
    AS $$
    DECLARE
        v_total numeric(14,4);
    BEGIN
        SELECT sum(net_amount) INTO v_total
        FROM "acme-invoicing".invoice
        WHERE mandant_id = p_mandant;
        RETURN coalesce(v_total, 0);
    END;
    $$;

CREATE FUNCTION "acme-invoicing".invoice_total(p_mandant integer, p_status text)
    RETURNS numeric
    LANGUAGE sql
    AS $$
    SELECT coalesce(sum(net_amount), 0)
    FROM "acme-invoicing".invoice
    WHERE mandant_id = p_mandant AND status = p_status
    $$;

CREATE PROCEDURE "acme-invoicing".touch_invoice(p_id integer)
    LANGUAGE plpgsql
    AS $$
    BEGIN
        UPDATE "acme-invoicing".invoice SET issued_at = now() WHERE id = p_id;
    END;
    $$;

-- A trigger, with a WHEN condition the server re-prints.
CREATE FUNCTION "acme-invoicing".stamp_receipt() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        NEW.paid_at := now();
        RETURN NEW;
    END;
    $$;

CREATE TRIGGER receipt_stamp
    BEFORE INSERT OR UPDATE ON "acme-invoicing".receipt
    FOR EACH ROW
    WHEN (NEW.amount > 0)
    EXECUTE FUNCTION "acme-invoicing".stamp_receipt();

-- An extension, so the extension query has a row that is not plpgsql.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
