"""The comparable representation of each catalog object.

Three rules hold for every class here:

1. Values are **already canonical** when the object is constructed. The diff engine only ever
   compares with ``==``; it never normalises. That keeps normalisation in one place and makes
   it testable on its own.
2. The pre-normalisation text lives in :class:`RawValues`, which is excluded from equality.
   Reports show what the server actually said; equality uses the canonical form.
3. Nothing here is runtime state. A sequence's ``last_value``, a matview's populated flag and
   a table's row estimate all differ between environments by design and are never captured.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from .keys import ObjectKey

#: ``attidentity``: ``'a'`` = GENERATED ALWAYS, ``'d'`` = GENERATED BY DEFAULT, ``None`` = neither.
Identity = Literal["a", "d"]

#: Canonical stand-in for a ``nextval()`` default on a sequence this column owns.
#:
#: The sequence's *name* differs between environments (``t_id_seq`` here, ``t_id_seq1`` there
#: after some historical rename), so comparing the literal default reports drift on every
#: serial column in the database. The strategy is what matters, not the generated name.
SERIAL_SENTINEL = "__SERIAL__"


@dataclass(frozen=True, slots=True)
class RawValues:
    """Pre-normalisation text, for display only.

    Always attached with ``compare=False`` so it cannot influence equality.
    """

    values: dict[str, str] = field(default_factory=dict)

    def get(self, attribute: str, fallback: str | None = None) -> str | None:
        """Raw text for ``attribute``, or ``fallback`` when it was not captured."""
        return self.values.get(attribute, fallback)


def _raw() -> RawValues:
    return RawValues()


@dataclass(frozen=True, slots=True)
class Table:
    """A table, partitioned parent, or partition leaf."""

    key: ObjectKey
    persistence: str
    """``relpersistence``: ``p`` permanent, ``u`` unlogged, ``t`` temporary.

    Unlogged in one environment and permanent in another is real drift: it silently changes
    crash-recovery behaviour.
    """
    is_partitioned: bool = False
    is_partition: bool = False
    partition_key: str | None = None
    """``pg_get_partkeydef`` of a partitioned parent, canonicalised."""
    partition_bound: str | None = None
    """``pg_get_expr(relpartbound)`` of a leaf, canonicalised."""

    partition_count: int | None = None
    """How many leaf partitions this parent has, when it is partitioned.

    A count rather than the leaves themselves. Leaf partitions are created by a maintenance job on a
    schedule, not by a migration, so production legitimately holds sixty monthly partitions where a
    development database holds two. Inventorying them individually would put fifty-eight findings in
    the report and bury everything else; the count is compared at INFO so the difference is visible
    without being treated as drift.
    """

    reloptions: tuple[str, ...] = ()
    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)


@dataclass(frozen=True, slots=True)
class Column:
    """One column of a table or view."""

    key: ObjectKey

    ordinal: int
    """Position among the live columns, counted densely from 1.

    Never ``attnum``: that has holes wherever a column was ever dropped, which would report
    drift on every column after the hole in any database that has had a ``DROP COLUMN``.
    """

    data_type: str
    """Canonical type, from ``format_type(atttypid, atttypmod)``.

    One source of truth on purpose. Rebuilding this from ``information_schema``'s
    ``data_type`` plus length, precision and scale columns is where homegrown comparers go
    wrong.
    """

    is_nullable: bool
    """From ``pg_attribute.attnotnull`` only.

    PostgreSQL 17 additionally exposes NOT NULL as a ``pg_constraint`` row of type ``'n'``;
    reading nullability from constraints would report one phantom constraint per column when
    comparing a 15 against a 17.
    """

    default: str | None = None
    """Canonical default expression, or :data:`SERIAL_SENTINEL` for an owned-sequence default."""

    identity: Identity | None = None
    generated: str | None = None
    """Canonical ``GENERATED ALWAYS AS (...) STORED`` expression.

    Kept separate from :attr:`default`: a stored generated column and a defaulted column are
    not the same thing, even when the expression matches.
    """

    collation: str | None = None
    """Non-default collation name.

    Compared, but auto-suppressed when the two databases' own collations differ: a
    ``de_DE.utf8`` production database against an ``en_US.utf8`` container would otherwise
    report every text column as drift.
    """

    sequence_name: str | None = None
    """The owned sequence behind a serial default. Reported, never compared."""

    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def is_serial(self) -> bool:
        """Whether the default is a ``nextval()`` on a sequence this column owns."""
        return self.default == SERIAL_SENTINEL

    @property
    def autoincrement(self) -> str | None:
        """Which autoincrement strategy this column uses, if any.

        ``serial`` and ``GENERATED BY DEFAULT AS IDENTITY`` both produce an autoincrementing
        integer, but they are genuinely different objects, so they are reported as drift
        rather than silently treated as equal.
        """
        if self.identity is not None:
            return f"identity:{self.identity}"
        if self.is_serial:
            return "serial"
        return None


#: ``contype`` values, spelled out for reports.
CONSTRAINT_KINDS: dict[str, str] = {
    "p": "primary key",
    "u": "unique",
    "f": "foreign key",
    "c": "check",
    "x": "exclusion",
}

#: ``confupdtype``/``confdeltype`` — what a foreign key does when the referenced row changes.
#: ``a`` is NO ACTION, the default, and is not the same as ``r`` RESTRICT: NO ACTION can be
#: deferred, RESTRICT cannot.
REFERENTIAL_ACTIONS: dict[str, str] = {
    "a": "NO ACTION",
    "r": "RESTRICT",
    "c": "CASCADE",
    "n": "SET NULL",
    "d": "SET DEFAULT",
}

#: ``confmatchtype``.
MATCH_TYPES: dict[str, str] = {"f": "FULL", "p": "PARTIAL", "s": "SIMPLE"}


@dataclass(frozen=True, slots=True)
class Constraint:
    """A primary key, unique, foreign key, check or exclusion constraint."""

    key: ObjectKey

    contype: str
    """``p``, ``u``, ``f``, ``c`` or ``x``."""

    columns: tuple[str, ...] = ()
    """Constrained column *names*, in the constraint's own order.

    Names rather than attribute numbers: two databases whose columns were added in a different
    order have different numbers for the same constraint.
    """

    references_schema: str | None = None
    references_name: str | None = None
    references_columns: tuple[str, ...] = ()

    on_update: str | None = None
    on_delete: str | None = None
    """Referential actions. A foreign key that cascades in one environment and restricts in
    another will behave differently the first time a row is deleted."""

    match_type: str | None = None
    deferrable: bool = False
    deferred: bool = False

    validated: bool = True
    """``convalidated``.

    A ``NOT VALID`` foreign key is *not* enforced for existing rows. One environment validated and
    another not is a real difference, and an easy one to create by accident: adding a constraint
    ``NOT VALID`` to avoid a long lock, then never validating it.
    """

    expression: str | None = None
    """Canonical CHECK or EXCLUDE expression."""

    backing_index: str | None = None
    """Name of the index PostgreSQL created for this constraint.

    Recorded so a report can explain where an index went, and never compared: the name is
    generated, and the index itself is excluded from the index inventory to avoid reporting every
    primary key twice.
    """

    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def kind_label(self) -> str:
        """``primary key``, ``foreign key`` and so on."""
        return CONSTRAINT_KINDS.get(self.contype, self.contype)

    @property
    def references(self) -> str | None:
        """``schema.table(col, col)`` for a foreign key."""
        if self.references_name is None:
            return None
        target = f"{self.references_schema}.{self.references_name}"
        if self.references_columns:
            target += "(" + ", ".join(self.references_columns) + ")"
        return target

    @property
    def referential_actions(self) -> str | None:
        """``ON UPDATE x ON DELETE y``, or ``None`` when this is not a foreign key."""
        if self.contype != "f":
            return None
        update = REFERENTIAL_ACTIONS.get(self.on_update or "a", self.on_update or "")
        delete = REFERENTIAL_ACTIONS.get(self.on_delete or "a", self.on_delete or "")
        return f"ON UPDATE {update} ON DELETE {delete}"


@dataclass(frozen=True, slots=True)
class IndexKey:
    """One key of an index: the column or expression, plus how it is ordered."""

    expression: str
    """A column name, or a canonical expression."""
    is_expression: bool = False
    opclass: str | None = None
    """Operator class name, recorded only when it is not the type's default.

    A non-default opclass changes which queries the index can serve — ``varchar_pattern_ops``
    supports ``LIKE 'x%'`` and the default does not.
    """
    collation: str | None = None
    descending: bool = False
    nulls_first: bool = False
    included: bool = False
    """An INCLUDE column: stored in the index but not part of its key."""

    def display(self) -> str:
        parts = [self.expression]
        if self.opclass:
            parts.append(self.opclass)
        if self.collation:
            parts.append(f'COLLATE "{self.collation}"')
        if self.descending:
            parts.append("DESC")
        if self.nulls_first:
            parts.append("NULLS FIRST")
        return " ".join(parts)


@dataclass(frozen=True, slots=True)
class Index:
    """An index that is not merely backing a constraint."""

    key: ObjectKey
    table: str
    access_method: str = "btree"
    is_unique: bool = False
    keys: tuple[IndexKey, ...] = ()
    predicate: str | None = None
    """Canonical ``WHERE`` clause of a partial index.

    A partial index in one environment and a full one in another satisfies different queries, so
    this is compared rather than treated as a detail.
    """
    nulls_not_distinct: bool = False
    """PostgreSQL 15's ``UNIQUE NULLS NOT DISTINCT``. Changes what the index actually enforces."""
    is_valid: bool = True
    r"""``indisvalid``.

    False means a ``CREATE INDEX CONCURRENTLY`` failed and left an index the planner will not use.
    Easy to miss in ``\d`` output, so it is worth an error.
    """
    reloptions: tuple[str, ...] = ()
    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def key_columns(self) -> tuple[str, ...]:
        """Display form of the key columns, in order, excluding INCLUDE columns."""
        return tuple(k.display() for k in self.keys if not k.included)

    @property
    def included_columns(self) -> tuple[str, ...]:
        """INCLUDE column names, in order."""
        return tuple(k.expression for k in self.keys if k.included)

    @property
    def structure(self) -> str:
        """One-line description of everything except the name.

        What "the same index under a different name" means, and what the report shows so a reader
        can see immediately whether a name difference is the only difference.
        """
        parts = ["unique" if self.is_unique else "non-unique", self.access_method]
        parts.append("(" + ", ".join(self.key_columns) + ")")
        if self.included_columns:
            parts.append("INCLUDE (" + ", ".join(self.included_columns) + ")")
        if self.nulls_not_distinct:
            parts.append("NULLS NOT DISTINCT")
        if self.predicate:
            parts.append(f"WHERE {self.predicate}")
        return " ".join(parts)


@dataclass(frozen=True, slots=True)
class View:
    """A view or a materialized view."""

    key: ObjectKey
    is_materialized: bool = False

    columns: tuple[str, ...] = ()
    """The view's resolved column names, in order.

    Compared at error level, and separately from the body. A consumer breaks when a column
    disappears, regardless of how the query behind it was rewritten — and unlike the body, the
    column list does not change spelling between PostgreSQL releases.
    """

    definition: str | None = None
    """Canonical body, from ``pg_get_viewdef``.

    The server re-prints this from its parse tree, so its formatting changes between major releases.
    Compared at warning level and downgraded further under version skew.
    """

    reloptions: tuple[str, ...] = ()
    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)


@dataclass(frozen=True, slots=True)
class Sequence:
    """A sequence.

    Its *position* is deliberately absent. ``last_value`` and ``is_called`` are runtime state that
    differ between environments by definition — a production sequence has issued more values than a
    QA one — and comparing them would report every sequence in the database as drifted.
    """

    key: ObjectKey
    data_type: str = "int8"
    start_value: int = 1
    increment: int = 1
    min_value: int | None = None
    max_value: int | None = None
    cache_size: int = 1
    cycles: bool = False

    owned_by: str | None = None
    """``table.column`` this sequence belongs to, for a ``serial``.

    Recorded, not compared: the column already reports its autoincrement strategy, and this
    sequence's own generated name diverges between environments.
    """

    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)


#: ``provolatile``: how freely the planner may cache a routine's result.
VOLATILITY: dict[str, str] = {"i": "IMMUTABLE", "s": "STABLE", "v": "VOLATILE"}

#: ``proparallel``.
PARALLEL_SAFETY: dict[str, str] = {"s": "SAFE", "r": "RESTRICTED", "u": "UNSAFE"}

#: ``prokind``.
ROUTINE_KINDS: dict[str, str] = {
    "f": "function",
    "p": "procedure",
    "a": "aggregate",
    "w": "window function",
}


@dataclass(frozen=True, slots=True)
class Routine:
    """A function or procedure."""

    key: ObjectKey
    """``name`` includes the identity argument list, because overloads are distinct objects that
    happen to share a name."""

    prokind: str = "f"
    language: str = "plpgsql"
    return_type: str | None = None
    returns_set: bool = False
    arguments: str | None = None
    """Full argument list including defaults, for display."""

    body: str | None = field(default=None, compare=False, repr=False)
    """Canonical body text, for display and diffing.

    ``None`` in an inventory written at schema version 1, which had only the hash. Excluded from
    equality: it is derived from the same source as :attr:`body_hash`, which is what decides
    whether two routines match, and a version 1 capture (``None``) must still equal a fresh one.
    """

    body_hash: str | None = None
    """SHA-256 of the canonical body.

    A hash rather than the text, and derived from ``prosrc`` rather than
    ``pg_get_functiondef``: that function re-prints the whole CREATE statement, and its header
    formatting changes between major releases, so comparing it reports every routine as changed.
    """

    volatility: str = "v"
    strict: bool = False
    security_definer: bool = False
    parallel_safety: str = "u"
    argument_defaults: str | None = None

    config: tuple[str, ...] = ()
    """``proconfig``, e.g. ``search_path=public``.

    Compared because a routine with a pinned ``search_path`` in one environment and not in another
    is a real behavioural *and* security difference, not a detail.
    """

    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def kind_label(self) -> str:
        return ROUTINE_KINDS.get(self.prokind, self.prokind)

    @property
    def volatility_label(self) -> str:
        return VOLATILITY.get(self.volatility, self.volatility)

    @property
    def parallel_label(self) -> str:
        return PARALLEL_SAFETY.get(self.parallel_safety, self.parallel_safety)

    @property
    def signature(self) -> str:
        """``schema.name(args) RETURNS type``, for display."""
        returns = f" RETURNS {self.return_type}" if self.return_type else ""
        return f"{self.key.schema}.{self.key.name}{returns}"


#: ``tgtype`` bit flags, from PostgreSQL's ``pg_trigger.h``.
TRIGGER_ROW = 1 << 0
TRIGGER_BEFORE = 1 << 1
TRIGGER_INSERT = 1 << 2
TRIGGER_DELETE = 1 << 3
TRIGGER_UPDATE = 1 << 4
TRIGGER_TRUNCATE = 1 << 5
TRIGGER_INSTEAD = 1 << 6


@dataclass(frozen=True, slots=True)
class Trigger:
    """A user trigger.

    Internal triggers — the ones PostgreSQL creates to enforce foreign keys — are never captured. A
    200-table schema has thousands of them, and every one would be reported.
    """

    key: ObjectKey
    function: str | None = None
    timing: str = "BEFORE"
    """``BEFORE``, ``AFTER`` or ``INSTEAD OF``."""
    events: tuple[str, ...] = ()
    """``INSERT``, ``UPDATE``, ``DELETE``, ``TRUNCATE``, in a fixed order so two spellings of the
    same trigger compare equal."""
    level: str = "ROW"
    """``ROW`` or ``STATEMENT``."""

    enabled: str = "O"
    """``tgenabled``: ``O`` origin, ``D`` disabled, ``R`` replica, ``A`` always.

    A trigger disabled in one environment is the classic production-only workaround, and it is
    invisible to anything that only checks whether the trigger exists at all.
    """

    condition: str | None = None
    """Canonical ``WHEN`` clause."""
    arguments: tuple[str, ...] = ()
    deferrable: bool = False
    deferred: bool = False
    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def disabled(self) -> bool:
        return self.enabled == "D"

    @property
    def signature(self) -> str:
        """``AFTER INSERT OR UPDATE FOR EACH ROW``, for display."""
        events = " OR ".join(self.events)
        return f"{self.timing} {events} FOR EACH {self.level}"


@dataclass(frozen=True, slots=True)
class UserType:
    """An enum, domain, composite or range type."""

    key: ObjectKey
    typtype: str = "e"
    """``e`` enum, ``d`` domain, ``c`` composite, ``r``/``m`` range."""

    labels: tuple[str, ...] = ()
    """An enum's labels, **in sort order**.

    Never the raw ``enumsortorder`` values: those become fractional after
    ``ALTER TYPE ... ADD VALUE BEFORE`` and differ between two databases holding the same labels.
    The order itself matters, because it defines the type's comparison operators.
    """

    base_type: str | None = None
    """A domain's underlying type, or a range's subtype."""
    not_null: bool = False
    default: str | None = None
    constraints: tuple[str, ...] = ()
    """A domain's CHECK constraints, canonicalised."""

    attributes: tuple[str, ...] = ()
    """A composite type's ``name type`` pairs, in order."""

    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)

    @property
    def kind_label(self) -> str:
        return {
            "e": "enum",
            "d": "domain",
            "c": "composite type",
            "r": "range",
            "m": "multirange",
        }.get(self.typtype, self.typtype)


@dataclass(frozen=True, slots=True)
class Extension:
    """An installed extension.

    Compared as a unit — name and version — while the thousands of functions and types an
    extension installs are excluded from the object inventory. Otherwise postgis alone would
    dominate every report.
    """

    key: ObjectKey
    version: str | None = None
    raw: RawValues = field(default_factory=_raw, compare=False, repr=False)
