"""The brand mark: that the SVGs, the PNGs and the generator are all the same drawing.

`packaging/logo.py` is the mark. `media/*.svg` is the same geometry written out by hand, because an
SVG generated by a script is a file nobody can open and nudge, and a hand-written one is the only
form a designer or a slide deck can actually use. That hand copy is the risk: change a row width in
the generator, regenerate the PNGs, ship an SVG that no longer matches, and the logo on the website
is a different logo from the one in the dock. Nothing but this module notices.

So every number in the SVGs is pinned to the constant it came from, and the PNGs are checked for
existence and for declaring the size their name claims — a 32px file written at 1024 would still
open fine and still be wrong.
"""

from __future__ import annotations

import struct
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
MEDIA = ROOT / "media"

# The generator is not importable as a package — packaging/ is build tooling, not library code —
# so it is reached by path, the same way the build reaches it.
sys.path.insert(0, str(ROOT / "packaging"))
import logo  # noqa: E402

SVG_NS = "{http://www.w3.org/2000/svg}"

#: The lockups place the mark inside a `transform="scale(...)"` group, so their rects carry the
#: same numbers as the standalone mark. Every SVG here therefore holds the same grid.
LOCKUPS = ("logo.svg", "logo-inverse.svg")
MARKS = ("logo-mark.svg", "logo-mark-mono.svg")


def hexed(colour: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*colour)


def rects(name: str) -> list[dict[str, str]]:
    """Every `<rect>` in the file, attributes as written, in document order."""
    tree = ET.parse(MEDIA / name)
    return [dict(element.attrib) for element in tree.iter(f"{SVG_NS}rect")]


def box(rect: dict[str, str]) -> tuple[float, float, float, float]:
    """A rect's `x`/`y`/`width`/`height` as the left, top, right, bottom the generator uses."""
    x, y = float(rect["x"]), float(rect["y"])
    return (x, y, x + float(rect["width"]), y + float(rect["height"]))


@pytest.mark.parametrize("name", [*MARKS, *LOCKUPS])
def test_every_svg_parses(name):
    assert rects(name), f"{name} draws nothing"


@pytest.mark.parametrize("name", ["logo-mark.svg", *LOCKUPS])
def test_the_rows_are_the_generators_rows(name):
    """Six rows, in the generator's order, with the generator's colours.

    The drift row is the one that carries the meaning: lime, and shorter than the row opposite it.
    A hand edit that evened the widths up would leave a mark that no longer says anything.
    """
    drawn = [r for r in rects(name) if float(r["height"]) == logo.ROW_HEIGHT]
    expected = [(b, hexed(colour)) for b, colour in logo.ROWS]
    # The white rows sit in a `<g fill>`; the lime one carries its own fill.
    assert len(drawn) == len(expected), f"{name} has {len(drawn)} rows, not {len(expected)}"
    by_box = {box(r): r.get("fill") for r in drawn}
    for expected_box, colour in expected:
        assert expected_box in by_box, f"{name} is missing the row at {expected_box}"
        painted = by_box[expected_box]
        if colour == hexed(logo.LIME):
            assert painted == colour, f"{name}'s drift row is not lime"
        else:
            assert painted in (None, colour), f"{name} paints a plain row {painted}"


@pytest.mark.parametrize("name", ["logo-mark.svg", "logo-mark-mono.svg", *LOCKUPS])
def test_the_divider_is_the_generators_divider(name):
    drawn = [r for r in rects(name) if box(r) == logo.DIVIDER]
    assert drawn, f"{name} has no comparison rule at {logo.DIVIDER}"
    assert float(drawn[0]["rx"]) == logo.DIVIDER_RADIUS


@pytest.mark.parametrize("name", ["logo-mark.svg", "logo.svg"])
def test_the_ground_is_the_generators_ground(name):
    """The inverse lockup deliberately has no ground; everything else must have exactly this one."""
    drawn = [r for r in rects(name) if box(r) == logo.GROUND]
    assert drawn, f"{name} has no ground at {logo.GROUND}"
    assert float(drawn[0]["rx"]) == logo.GROUND_RADIUS
    assert drawn[0]["fill"] == hexed(logo.NAVY)


def test_the_inverse_lockup_drops_the_ground():
    """A navy ground on a navy rail is an invisible rectangle; the rows have to carry the shape."""
    assert not [r for r in rects("logo-inverse.svg") if box(r) == logo.GROUND]


def test_the_mono_mark_knocks_the_rows_out_rather_than_painting_them():
    """One ink. Painted rows would need a second, and would vanish on a single-colour print."""
    source = (MEDIA / "logo-mark-mono.svg").read_text(encoding="utf-8")
    assert 'mask="url(#rows)"' in source
    assert hexed(logo.LIME) not in source.lower(), "a mono mark with an accent is not mono"


@pytest.mark.parametrize("name", [*MARKS, *LOCKUPS])
def test_no_svg_invents_a_colour(name):
    """Every fill is a design token, or the black and white a mask is written in."""
    allowed = {
        hexed(logo.NAVY),
        hexed(logo.LIME),
        hexed(logo.WHITE),
        "#5b6a80",  # Tokens.muted, the wordmark's second line.
        "#000000",  # The mask's own alphabet, not a brand colour.
    }
    tree = ET.parse(MEDIA / name)
    painted = {
        element.attrib["fill"].lower() for element in tree.iter() if "fill" in element.attrib
    }
    assert painted <= allowed, f"{name} paints with {painted - allowed}"


def test_the_wordmark_uses_the_bundled_display_family():
    """Archivo is what `gui/fonts.py` installs; a lockup in another face is another brand."""
    for name in LOCKUPS:
        tree = ET.parse(MEDIA / name)
        families = [
            element.attrib["font-family"]
            for element in tree.iter()
            if "font-family" in element.attrib
        ]
        assert families, f"{name} sets no typeface"
        assert all(family.startswith("Archivo") for family in families)
        weights = {
            element.attrib["font-weight"]
            for element in tree.iter()
            if "font-weight" in element.attrib
        }
        # 700 is the only weight bundled; anything else is synthesised by whatever renders it.
        assert weights == {"700"}


@pytest.mark.parametrize("size", [1024, 512, 256, 128, 64, 32, 16])
def test_each_png_exists_and_is_the_size_its_name_claims(size):
    """A downsampled 1024 would open fine at 16px and look like grey mush; the name must be true."""
    path = MEDIA / f"logo-mark-{size}.png"
    assert path.is_file(), f"{path.name} is missing; run packaging/make_logo.py"
    header = path.read_bytes()[:33]
    assert header.startswith(b"\x89PNG\r\n\x1a\n")
    width, height = struct.unpack(">2I", header[16:24])
    assert (width, height) == (size, size)


def test_the_png_set_is_the_set_the_generator_writes():
    """A size added to the generator and not regenerated leaves a gap nobody notices until use."""
    generator = (ROOT / "packaging" / "make_logo.py").read_text(encoding="utf-8")
    declared = generator[
        generator.index("SIZES = (") : generator.index(")", generator.index("SIZES = ("))
    ]
    sizes = {int(part) for part in declared.removeprefix("SIZES = (").split(",") if part.strip()}
    on_disk = {int(p.stem.rsplit("-", 1)[1]) for p in MEDIA.glob("logo-mark-*.png")}
    assert sizes == on_disk
